version: '3.2'

services:
  etny-swift-stream:
    container_name: etny-swift-stream
    image: quay.io/minio/minio:RELEASE.2023-03-13T19-46-17Z
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: swiftstreamadmin
      MINIO_ROOT_PASSWORD: swiftstreamadmin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://docker:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
